/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2016-07-29 02:28:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t\tbody \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tleft: 50%;\r\n");
      out.write("\t\t\ttop: 50%;\r\n");
      out.write("\t\t\tmargin-left: -120px;\r\n");
      out.write("\t\t\tmargin-top: -130px;\t\t\r\n");
      out.write(" \t\t\tbackground-color:#333;\r\n");
      out.write(" \t\t\tfont-family: \"微软雅黑\";\r\n");
      out.write(" \t\t\tcolor: white; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.onload = function()\r\n");
      out.write("\t\t{\t\r\n");
      out.write("\t\t\tvar id = document.getElementById(\"id\");\r\n");
      out.write("\t\t\tvar aLabel = document.getElementsByTagName(\"label\");\r\n");
      out.write("\t\t\tvar aForm = document.getElementsByTagName(\"form\");\r\n");
      out.write("\t\t\tvar oTel = document.getElementById(\"phone\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\taForm[0].onsubmit=function(){\r\n");
      out.write("\t\t\t\tif(id.value != \"\" && !isNaN(id.value)){\r\n");
      out.write("\t\t\t\t\taLabel[0].innerHTML = \"√\";\r\n");
      out.write("\t\t\t\t\tif(parseInt(oTel.value) > 100000000000||parseInt(oTel.value) < 9999999999){\r\n");
      out.write("\t\t\t\t\t\taLabel[2].innerHTML = \"×\";\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\taLabel[2].innerHTML = \"√\";\r\n");
      out.write("\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\taLabel[0].innerHTML = \"×\";\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>会员信息添加页面</h1>\r\n");
      out.write("\t<form action=\"addAct\" method=\"post\">\r\n");
      out.write("\t\t编号:<input type=\"text\" id=\"id\" name=\"id\"><label>*</label><br><br>\r\n");
      out.write("\t\t名字:<input type=\"text\" id=\"name\" name=\"name\"><label>*30位以内</label><br><br>\r\n");
      out.write("\t\t积分:<input type=\"text\" id=\"score\" name=\"score\"><br><br>\r\n");
      out.write("\t\t手机:<input type=\"text\" id=\"phone\" name=\"phone\"><label>*11位</label><br><br>\r\n");
      out.write("\t\t<input type=\"radio\" name=\"sex\" value=\"1\">男\r\n");
      out.write("\t\t<input type=\"radio\" name=\"sex\" value=\"2\">女<br><br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"添加\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
