/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2016-07-28 07:45:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");

	    String id = request.getParameter("id");
		String name = request.getParameter("name");
		String score = request.getParameter("score");
		String phone = request.getParameter("phone");
		String sex = request.getParameter("sex");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t\tbody \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tleft: 50%;\r\n");
      out.write("\t\t\ttop: 50%;\r\n");
      out.write("\t\t\tmargin-left: -120px;\r\n");
      out.write("\t\t\tmargin-top: -150px;\t\t\r\n");
      out.write(" \t\t\tbackground-color:#333;\r\n");
      out.write(" \t\t\tfont-family: \"微软雅黑\";\r\n");
      out.write(" \t\t\tcolor: white; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>会员信息修改页面</h1>\r\n");
      out.write("\t<form action=\"updateAct\" method=\"post\">\r\n");
      out.write("\t\t编号:<input type=\"text\" name=\"id\" value=\"");
      out.print(id );
      out.write("\" readonly=\"readonly\" style=\"background-color: #999;\"><br><br>\r\n");
      out.write("\t\t名字:<input type=\"text\" name=\"name\" value=\"");
      out.print(name );
      out.write("\"><label>*30位以内</label><br><br>\r\n");
      out.write("\t\t积分:<input type=\"text\" name=\"score\" value=\"");
      out.print(score );
      out.write("\"><br><br>\r\n");
      out.write("\t\t手机:<input type=\"text\" name=\"phone\" value=\"");
      out.print(phone );
      out.write("\"><label>*11位</label><br><br>\r\n");
      out.write("\t\t<input type=\"radio\" name=\"sex\" value=\"1\"\t");
if(sex.equals("1")){ 
      out.write("\tchecked=\"checked\"\t");
} 
      out.write("\t>男\r\n");
      out.write("\t\t<input type=\"radio\" name=\"sex\" value=\"2\"\t");
if(sex.equals("2")){ 
      out.write("\tchecked=\"checked\"\t");
} 
      out.write("\t>女<br><br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"修改\">\r\n");
      out.write("\t\t<a href=\"home.jsp\"><input type=\"button\" value=\"取消\"></a>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
