/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2016-07-27 03:04:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>数据交互输入页</title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\tbody \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tleft: 50%;\r\n");
      out.write("\t\t\ttop: 50%;\r\n");
      out.write("\t\t\tmargin-left: -120px;\r\n");
      out.write("\t\t\tmargin-top: -130px;\t\t\r\n");
      out.write(" \t\t\tbackground-color:#333;\r\n");
      out.write(" \t\t\tfont-family: \"微软雅黑\";\r\n");
      out.write(" \t\t\tcolor: white; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.onload = function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar aInput=document.getElementsByTagName(\"input\");\r\n");
      out.write("\t\t\tvar oTitle=document.getElementById(\"head\");\r\n");
      out.write("\t\t\tvar aLabel=document.getElementsByTagName(\"label\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\taInput[4].onmouseover = function()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(aInput[0].value.length <= 18 && aInput[0].value.length >= 5)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\taLabel[0].innerHTML = \"√\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t{\t\r\n");
      out.write("\t\t\t\t\taLabel[0].innerHTML = \"×\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(aInput[1].value.length == 6)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\taLabel[1].innerHTML = \"√\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\taLabel[1].innerHTML = \"×\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//判断账号\r\n");
      out.write("\t\t\t\tif(isNaN(aInput[0].value))\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\taLabel[0].innerHTML = \"错误，请输入数字\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//判断密码\r\n");
      out.write("\t\t\t\tif(isNaN(aInput[1].value))\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\taLabel[1].innerHTML = \"错误，请输入数字\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(aLabel[0].innerHTML == \"√\" && aLabel[1].innerHTML == \"√\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\toTitle.innerHTML = \"Welcome.\";\r\n");
      out.write("\t\t\t\t\taInput[4].type = \"submit\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\toTitle.innerHTML = \"输入错误，请重新输入\";\r\n");
      out.write("\t\t\t\t\taInput[4].type = \"button\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\taInput[4].onmouseout = function()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\toTitle.innerHTML = \"注册画面\";\r\n");
      out.write("\t\t\t\taLabel[0].innerHTML = \"*5-18位数字\";\r\n");
      out.write("\t\t\t\taLabel[1].innerHTML = \"*6位数字\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 id=\"head\">注册画面</h1>\r\n");
      out.write("\t<form action=\"MyServlet\" method=\"post\">\r\n");
      out.write("\t\t账号：<input name=\"id\" type=\"text\"><label>*5-18位数字</label><br><br>\r\n");
      out.write("\t\t密码：<input name=\"pw\" type=\"password\" maxlength=\"6\"><label>*6位数字</label><br><br>\r\n");
      out.write("\t\t<input type=\"radio\" value=\"male\" checked=\"checked\" name=\"sex\">男\r\n");
      out.write("\t\t<input type=\"radio\" value=\"female\" name=\"sex\">女<br><br>\r\n");
      out.write("\t\t<select name=\"province\">\r\n");
      out.write("\t\t\t<option value=\"unchoose\">请选择</option>\r\n");
      out.write("\t\t\t<option value=\"1\">浙江</option>\r\n");
      out.write("\t\t\t<option value=\"2\">江苏</option>\r\n");
      out.write("\t\t\t<option value=\"3\">上海</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"注册\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
